name: Run lint and static analyis checks
on:
  pull_request:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this git repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Project Syntax Verification
        run: make docker/run target=lint
